// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjkhixneqwltxbeoeagk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qa2hpeG5lcXdsdHhiZW9lYWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjM0MjgsImV4cCI6MjA2MjE5OTQyOH0.Bj_NdJFls4LesfIwvNXzHqrTpiz49ourUoDbDGfR7qs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);